#!/usr/bin/env python3
"""Generate a C++ header embedding SPIR-V binaries as uint32_t arrays.

Usage: gen_spirv_header.py <shared_8> <shared_16> <shared_32>
                           <plain_8> <plain_16> <plain_32>
                           <bm3d> <bm3d_agg>
                           <gaussblur_8_gauss> <gaussblur_8_vert> <gaussblur_8_horiz>
                           <gaussblur_16_gauss> <gaussblur_16_vert> <gaussblur_16_horiz>
                           <gaussblur_16h_gauss> <gaussblur_16h_vert> <gaussblur_16h_horiz>
                            <gaussblur_32_gauss> <gaussblur_32_vert> <gaussblur_32_horiz>
                            <dfttest_16_pad_slot> <dfttest_16_pad_direct> <dfttest_16_col2im>
                            <dfttest_16_fused_r0> <dfttest_16_fused_r1> <dfttest_16_fused_r2> <dfttest_16_fused_r3>
                             <dfttest_32_pad_slot> <dfttest_32_pad_direct> <dfttest_32_col2im>
                             <dfttest_32_fused_r0> <dfttest_32_fused_r1> <dfttest_32_fused_r2> <dfttest_32_fused_r3>
                             <nlmeans_16_weight> <nlmeans_16_acc> <nlmeans_16_finish> <nlmeans_16_pad>
                             <nlmeans_32_weight> <nlmeans_32_acc> <nlmeans_32_finish> <nlmeans_32_pad>
                             <out header>
"""

import sys
from pathlib import Path

def emit_spv(f, name: str, path: Path) -> None:
    data = path.read_bytes()
    words = (data[i:i+4] for i in range(0, len(data), 4))
    f.write(f"static const uint32_t {name}_spv[] = {{\n    ")
    count = 0
    for word in words:
        value = int.from_bytes(word, "little")
        f.write(f"0x{value:08x}u, ")
        count += 1
        if count % 8 == 0:
            f.write("\n    ")
    f.write(f"\n}};\n")
    f.write(f"static const size_t {name}_spv_size = sizeof({name}_spv);\n\n")

def main() -> None:
    if len(sys.argv) != 44:
        print("usage: gen_spirv_header.py <...dfttest binaries...> "
              "<nlmeans_16_weight> <nlmeans_16_acc> <nlmeans_16_finish> "
              "<nlmeans_32_weight> <nlmeans_32_acc> <nlmeans_32_finish> <out header>")
        sys.exit(1)

    shared_8, shared_16, shared_32, plain_8, plain_16, plain_32, bm3d, bm3d_agg, \
        gb_8_g, gb_8_v, gb_8_h, gb_16_g, gb_16_v, gb_16_h, \
        gb_16h_g, gb_16h_v, gb_16h_h, gb_32_g, gb_32_v, gb_32_h, \
        df_16_ps, df_16_pd, df_16_c, df_16_f0, df_16_f1, df_16_f2, df_16_f3, \
        df_32_ps, df_32_pd, df_32_c, df_32_f0, df_32_f1, df_32_f2, df_32_f3, \
        nl_16_w, nl_16_a, nl_16_f, nl_16_p, nl_32_w, nl_32_a, nl_32_f, nl_32_p, \
        out_path = (Path(a) for a in sys.argv[1:])
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w") as f:
        f.write("// Generated by gen_spirv_header.py - do not edit\n\n")
        f.write("#pragma once\n\n")
        emit_spv(f, "kernel_shared_8", shared_8)
        emit_spv(f, "kernel_shared_16", shared_16)
        emit_spv(f, "kernel_shared_32", shared_32)
        emit_spv(f, "kernel_plain_8", plain_8)
        emit_spv(f, "kernel_plain_16", plain_16)
        emit_spv(f, "kernel_plain_32", plain_32)
        emit_spv(f, "bm3d", bm3d)
        emit_spv(f, "bm3d_agg", bm3d_agg)
        emit_spv(f, "gaussblur_8_gauss", gb_8_g)
        emit_spv(f, "gaussblur_8_vert", gb_8_v)
        emit_spv(f, "gaussblur_8_horiz", gb_8_h)
        emit_spv(f, "gaussblur_16_gauss", gb_16_g)
        emit_spv(f, "gaussblur_16_vert", gb_16_v)
        emit_spv(f, "gaussblur_16_horiz", gb_16_h)
        emit_spv(f, "gaussblur_16h_gauss", gb_16h_g)
        emit_spv(f, "gaussblur_16h_vert", gb_16h_v)
        emit_spv(f, "gaussblur_16h_horiz", gb_16h_h)
        emit_spv(f, "gaussblur_32_gauss", gb_32_g)
        emit_spv(f, "gaussblur_32_vert", gb_32_v)
        emit_spv(f, "gaussblur_32_horiz", gb_32_h)
        emit_spv(f, "dfttest_16_pad_slot", df_16_ps)
        emit_spv(f, "dfttest_16_pad_direct", df_16_pd)
        emit_spv(f, "dfttest_16_col2im", df_16_c)
        emit_spv(f, "dfttest_16_fused_r0", df_16_f0)
        emit_spv(f, "dfttest_16_fused_r1", df_16_f1)
        emit_spv(f, "dfttest_16_fused_r2", df_16_f2)
        emit_spv(f, "dfttest_16_fused_r3", df_16_f3)
        emit_spv(f, "dfttest_32_pad_slot", df_32_ps)
        emit_spv(f, "dfttest_32_pad_direct", df_32_pd)
        emit_spv(f, "dfttest_32_col2im", df_32_c)
        emit_spv(f, "dfttest_32_fused_r0", df_32_f0)
        emit_spv(f, "dfttest_32_fused_r1", df_32_f1)
        emit_spv(f, "dfttest_32_fused_r2", df_32_f2)
        emit_spv(f, "dfttest_32_fused_r3", df_32_f3)
        emit_spv(f, "nlmeans_16_weight", nl_16_w)
        emit_spv(f, "nlmeans_16_acc", nl_16_a)
        emit_spv(f, "nlmeans_16_finish", nl_16_f)
        emit_spv(f, "nlmeans_16_pad", nl_16_p)
        emit_spv(f, "nlmeans_32_weight", nl_32_w)
        emit_spv(f, "nlmeans_32_acc", nl_32_a)
        emit_spv(f, "nlmeans_32_finish", nl_32_f)
        emit_spv(f, "nlmeans_32_pad", nl_32_p)

if __name__ == "__main__":
    main()
