#!/usr/bin/env python3
"""Generate a C++ header embedding SPIR-V binaries as uint32_t arrays.

Usage: gen_spirv_header.py --out <header> <spv files...>

Symbol names are derived from the input filenames, so adding a shader
variant only requires adding its glslc rule to CMakeLists.txt (which
appends to VK_SPV_OUTPUTS, passed through as the input list here) —
this script never needs editing for new variants.

Mapping: <stem>.spv -> <stem>_spv / <stem>_spv_size, where <stem> is the
basename without extension with '-' replaced by '_'. The header order is
sorted by symbol for deterministic output.
"""

import argparse
import re
import sys
from pathlib import Path

_SYMBOL_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def symbol_for(path: Path) -> str:
    stem = path.stem.replace("-", "_")
    if not _SYMBOL_RE.fullmatch(stem):
        raise ValueError(f"cannot derive a C identifier from {path.name!r}")
    return stem


def emit_spv(f, name: str, path: Path) -> None:
    data = path.read_bytes()
    words = (data[i:i + 4] for i in range(0, len(data), 4))
    f.write(f"static const uint32_t {name}_spv[] = {{\n    ")
    count = 0
    for word in words:
        value = int.from_bytes(word, "little")
        f.write(f"0x{value:08x}u, ")
        count += 1
        if count % 8 == 0:
            f.write("\n    ")
    f.write(f"\n}};\n")
    f.write(f"static const size_t {name}_spv_size = sizeof({name}_spv);\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="output header path")
    parser.add_argument("spv", nargs="+", help="input .spv files")
    args = parser.parse_args()

    inputs = [(symbol_for(Path(a)), Path(a)) for a in args.spv]
    seen: dict[str, str] = {}
    for sym, path in inputs:
        if sym in seen:
            print(f"error: duplicate symbol {sym!r} from {seen[sym]} and {path}",
                  file=sys.stderr)
            sys.exit(1)
        seen[sym] = str(path)
    for sym, path in inputs:
        if not path.is_file():
            print(f"error: missing input {path}", file=sys.stderr)
            sys.exit(1)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write("// Generated by gen_spirv_header.py - do not edit\n\n")
        f.write("#pragma once\n\n")
        for sym, path in sorted(inputs):
            emit_spv(f, sym, path)


if __name__ == "__main__":
    main()
