#!/usr/bin/env python3
"""Generate a C++ header embedding SPIR-V binaries as uint32_t arrays.

Usage: gen_spirv_header.py <shared_8> <shared_16> <shared_32>
                           <plain_8> <plain_16> <plain_32>
                           <bm3d> <bm3d_agg>
                           <gaussblur_8_gauss> <gaussblur_8_vert> <gaussblur_8_horiz>
                           <gaussblur_16_gauss> <gaussblur_16_vert> <gaussblur_16_horiz>
                           <gaussblur_16h_gauss> <gaussblur_16h_vert> <gaussblur_16h_horiz>
                           <gaussblur_32_gauss> <gaussblur_32_vert> <gaussblur_32_horiz>
                           <dfttest_8_pad> <dfttest_8_col2im>
                           <dfttest_8_fused_r0> <dfttest_8_fused_r1> <dfttest_8_fused_r2> <dfttest_8_fused_r3>
                           <dfttest_16_pad> <dfttest_16_col2im>
                           <dfttest_16_fused_r0> <dfttest_16_fused_r1> <dfttest_16_fused_r2> <dfttest_16_fused_r3>
                           <dfttest_32_pad> <dfttest_32_col2im>
                           <dfttest_32_fused_r0> <dfttest_32_fused_r1> <dfttest_32_fused_r2> <dfttest_32_fused_r3>
                           <out header>
"""

import sys
from pathlib import Path

def emit_spv(f, name: str, path: Path) -> None:
    data = path.read_bytes()
    words = (data[i:i+4] for i in range(0, len(data), 4))
    f.write(f"static const uint32_t {name}_spv[] = {{\n    ")
    count = 0
    for word in words:
        value = int.from_bytes(word, "little")
        f.write(f"0x{value:08x}u, ")
        count += 1
        if count % 8 == 0:
            f.write("\n    ")
    f.write(f"\n}};\n")
    f.write(f"static const size_t {name}_spv_size = sizeof({name}_spv);\n\n")

def main() -> None:
    if len(sys.argv) != 40:
        print("usage: gen_spirv_header.py <shared_8> <shared_16> <shared_32> <plain_8> <plain_16> <plain_32> <bm3d> <bm3d_agg> <gaussblur_8_*x3> <gaussblur_16_*x3> <gaussblur_16h_*x3> <gaussblur_32_*x3> <dfttest_8_pad> <dfttest_8_col2im> <dfttest_8_fused_r0..r3> <dfttest_16_pad> <dfttest_16_col2im> <dfttest_16_fused_r0..r3> <dfttest_32_pad> <dfttest_32_col2im> <dfttest_32_fused_r0..r3> <out header>")
        sys.exit(1)

    shared_8, shared_16, shared_32, plain_8, plain_16, plain_32, bm3d, bm3d_agg, \
        gb_8_g, gb_8_v, gb_8_h, gb_16_g, gb_16_v, gb_16_h, \
        gb_16h_g, gb_16h_v, gb_16h_h, gb_32_g, gb_32_v, gb_32_h, \
        df_8_p, df_8_c, df_8_f0, df_8_f1, df_8_f2, df_8_f3, \
        df_16_p, df_16_c, df_16_f0, df_16_f1, df_16_f2, df_16_f3, \
        df_32_p, df_32_c, df_32_f0, df_32_f1, df_32_f2, df_32_f3, \
        out_path = (Path(a) for a in sys.argv[1:])
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w") as f:
        f.write("// Generated by gen_spirv_header.py - do not edit\n\n")
        f.write("#pragma once\n\n")
        emit_spv(f, "kernel_shared_8", shared_8)
        emit_spv(f, "kernel_shared_16", shared_16)
        emit_spv(f, "kernel_shared_32", shared_32)
        emit_spv(f, "kernel_plain_8", plain_8)
        emit_spv(f, "kernel_plain_16", plain_16)
        emit_spv(f, "kernel_plain_32", plain_32)
        emit_spv(f, "bm3d", bm3d)
        emit_spv(f, "bm3d_agg", bm3d_agg)
        emit_spv(f, "gaussblur_8_gauss", gb_8_g)
        emit_spv(f, "gaussblur_8_vert", gb_8_v)
        emit_spv(f, "gaussblur_8_horiz", gb_8_h)
        emit_spv(f, "gaussblur_16_gauss", gb_16_g)
        emit_spv(f, "gaussblur_16_vert", gb_16_v)
        emit_spv(f, "gaussblur_16_horiz", gb_16_h)
        emit_spv(f, "gaussblur_16h_gauss", gb_16h_g)
        emit_spv(f, "gaussblur_16h_vert", gb_16h_v)
        emit_spv(f, "gaussblur_16h_horiz", gb_16h_h)
        emit_spv(f, "gaussblur_32_gauss", gb_32_g)
        emit_spv(f, "gaussblur_32_vert", gb_32_v)
        emit_spv(f, "gaussblur_32_horiz", gb_32_h)
        emit_spv(f, "dfttest_8_pad", df_8_p)
        emit_spv(f, "dfttest_8_col2im", df_8_c)
        emit_spv(f, "dfttest_8_fused_r0", df_8_f0)
        emit_spv(f, "dfttest_8_fused_r1", df_8_f1)
        emit_spv(f, "dfttest_8_fused_r2", df_8_f2)
        emit_spv(f, "dfttest_8_fused_r3", df_8_f3)
        emit_spv(f, "dfttest_16_pad", df_16_p)
        emit_spv(f, "dfttest_16_col2im", df_16_c)
        emit_spv(f, "dfttest_16_fused_r0", df_16_f0)
        emit_spv(f, "dfttest_16_fused_r1", df_16_f1)
        emit_spv(f, "dfttest_16_fused_r2", df_16_f2)
        emit_spv(f, "dfttest_16_fused_r3", df_16_f3)
        emit_spv(f, "dfttest_32_pad", df_32_p)
        emit_spv(f, "dfttest_32_col2im", df_32_c)
        emit_spv(f, "dfttest_32_fused_r0", df_32_f0)
        emit_spv(f, "dfttest_32_fused_r1", df_32_f1)
        emit_spv(f, "dfttest_32_fused_r2", df_32_f2)
        emit_spv(f, "dfttest_32_fused_r3", df_32_f3)

if __name__ == "__main__":
    main()
